### ISSUE TITLE
Dictionary Diffs UI Fixes

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/argo-docs#347]
- filtering bug (can filter on non present elements)
- description change css (green highlight)
- whole schema added css (green highlight)
- schema loading bug: won't load low => high version eg. 0.4 => 0.6 only 0.6 => 0.4
- minor css: min width on modal, add table row borders

**Comment by kcullion** [comment]
@ciaranschutte some more items (sorry if there's duplication - I don't quite understand the above items):
- [ ] I land on version 6. When I compare with version 5 - the donor file gets "added".  But really it would mean it got deleted in version 6. The newer version should takes precedence in the comparison
- [ ] Are the attributes not coming through? I can filter by them but I can't see them in the table
- [ ] could be related - when I compare, I don't see the old values in the attributes: 
![image](https://user-images.githubusercontent.com/18424138/90176439-ea007780-dd76-11ea-8980-5c74bba4f606.png)
- [ ] when I compare version 6 with 5, the counts says "5 new fields" - but that should just be 3 new fields

**Comment by ciaranschutte** [comment]
@kcullion  " when I do a comparison and refresh my screen, my comparison should persist instead of getting reset to not compare" new functionality

**Comment by kcullion** [comment]
ok thanks @ciaranschutte ...I'll break that piece into a new ticket for prioritization.

**Comment by kcullion** [comment]
Noticed a couple things, please ignore if you know about them!

- [ ] when a script is deleted - what you have is good...but instead of disabling the button - would it be easier to just cross out the script that's in this modal to be consistent with the other script update modal?
![image](https://user-images.githubusercontent.com/18424138/90776618-51af4900-e2c8-11ea-8d7f-379fac224659.png)

- [ ] when I filter on "conditional" - I get a field that is required
![image](https://user-images.githubusercontent.com/18424138/90776763-84594180-e2c8-11ea-9184-8f6efde1db02.png)

- [ ] add the horizontal borders in between rows so it's easier to distinguish when in diff view (borders can remain when not comparing too). See: https://zpl.io/VQjOpoW

**Comment by rosibaj** [comment]
@ciaranschutte since we have the one outstanding bug i will close this ticket as completed!
