### ISSUE TITLE
suffix .fq.gz or .fastq.gz   --->   *.fq.gz or *.fastq.gz

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-docs#401]
suffix .fq.gz or .fastq.gz   --->   *.fq.gz or *.fastq.gz
suffix .fq.bz2 or .fastq.bz2  ---> *.fq.bz2 or *.fastq.bz2

_Originally posted by @lindaxiang in https://github.com/icgc-argo/argo-docs/pull/398#discussion_r543633133_

there are some formatting errors here - resolve that so we can use the *

**Comment by ciaranschutte** [comment]
suffix .fq.gz or .fastq.gz ---> \*.fq.gz or \*.fastq.gz
suffix .fq.bz2 or .fastq.bz2 ---> \*.fq.bz2 or \*.fastq.bz2

docs are markdown so symbols often mean things rather than a plaintext file

use backslashy to display an actual asterik rather than a list? i think.
backslash will escape most symbols

**Comment by rosibaj** [comment]
fixed on Dictionary 1.10 branch - closing.
