### ISSUE TITLE
Doc Updates for Dictionary 1.14

### ISSUE THREAD

**Issue by b-f-chan** [icgc-argo/argo-docs#510]
Doc updates needed are:

- [x] Update Releases page (https://docs.icgc-argo.org/docs/release-notes/dictionary-releases)
- [x] Update ARGO documentation to delineate clearly between the use of "Unknown" vs. "Not applicable" in the ARGO clinical submissions (this is already a task in this ticket: https://github.com/icgc-argo/argo-dictionary/issues/347, but tracking here also)

**Comment by hknahal** [comment]
PR for Release notes and ARGO documentation update: https://github.com/icgc-argo/argo-docs/pull/512 Checks failing due to error in netlify (https://app.netlify.com/sites/argo-docs/deploys/62a126af87647a12fc9fcffb).
- added Release notes for Dictionary version 1.14
- added documentation on how to submit 'Unknown', 'Not applicable' and 'Cannot be accessed/determined'
- added documentation on how to submit Surgery file

**Comment by b-f-chan** [comment]
@b-f-chan reviewed the PRs and gave feedback, @hknahal has fixed; moving to awaiting release

**Comment by kcullion** [comment]
closing this as it was released!
